### ISSUE TITLE
L4 Practice Qs: Questions only?

### ISSUE THREAD

**Issue by eirenjacobson** [MT4113/2018#3]
Is there a version of [these practice questions](https://github.com/MT4113/2018/blob/master/Lectures/Lecture%204/Lect4PracticeQsWithSolutions.pdf) with questions only?

**Comment by lenthomas** [comment]
Yes, they are at the end of the lecture - see, e.g., the [notes](https://github.com/MT4113/2018/blob/master/Lectures/Lecture%204/lect4_notes.pdf).
